import { configureStore } from "@reduxjs/toolkit";
import {
  groupListReducer,
  nxtFollowupActionIdReducer,
  roleListReducer,
  roleSearchValueReducer,
  usersListReducer,
  userSearchValueReducer,
  allUsersListReducer,
  permissionsListReducer,
  dashboardModulePermissionListReducer,
  leadsModulePermissionListReducer,
  leadFollowupModulePermissionListReducer,
  customersModulePermissionListReducer,
  feesPendingModulePermissionListReducer,
  bulkSearchModulePermissionListReducer,
  serverModulePermissionListReducer,
  trainersModulePermissionListReducer,
  settingsModulePermissionListReducer,
  childUsersReducer,
  downlineUsersReducer,
  userPermissionsReducer,
  tableColumnsReducer,
} from "./Slice";

export const reduxStore = configureStore({
  devTools: true,
  reducer: {
    userslist: usersListReducer,
    usersearchvalue: userSearchValueReducer,
    alluserslist: allUsersListReducer,
    nxtfollowupactionid: nxtFollowupActionIdReducer,
    grouplist: groupListReducer,
    rolelist: roleListReducer,
    rolesearchvalue: roleSearchValueReducer,
    childusers: childUsersReducer,
    downlineusers: downlineUsersReducer,
    userpermissions: userPermissionsReducer,
    permissionslist: permissionsListReducer,
    dashboardmodulepermissionlist: dashboardModulePermissionListReducer,
    leadsmodulepermissionlist: leadsModulePermissionListReducer,
    leadfollowupmodulepermissionlist: leadFollowupModulePermissionListReducer,
    customersmodulepermissionlist: customersModulePermissionListReducer,
    feespendingmodulepermissionlist: feesPendingModulePermissionListReducer,
    bulksearchmodulepermissionlist: bulkSearchModulePermissionListReducer,
    servermodulepermissionlist: serverModulePermissionListReducer,
    trainersmodulepermissionlist: trainersModulePermissionListReducer,
    settingsmodulepermissionlist: settingsModulePermissionListReducer,
    tablecolumns: tableColumnsReducer,
  },
});
